name = "bngolg-v1"
main = "worker.js"
compatibility_date = "2024-12-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "bngold-db-v1"
database_id = "300412b0-d276-4975-bc7d-1c2f16f51ac9"

[vars]
APP_ENV = "production"
